version: '3.8'

services:
  voltaris-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voltaris-website
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:80"
    environment:
      - API_URL=${API_URL:-/api}
      - APP_ENV=${APP_ENV:-production}
      - PUBLIC_URL=${PUBLIC_URL:-}
      - REACT_APP_CUSTOM_VARIABLE=${REACT_APP_CUSTOM_VARIABLE:-default_value}
    networks:
      - voltaris-network
    # Uncomment for mounted volumes during development
    # volumes:
    #  - ./build:/usr/share/nginx/html:ro

  # Uncomment if you need a database
  # db:
  #   image: postgres:13-alpine
  #   container_name: voltaris-db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_PASSWORD=secure_password
  #     - POSTGRES_USER=voltaris
  #     - POSTGRES_DB=voltaris
  #   volumes:
  #     - voltaris-db-data:/var/lib/postgresql/data
  #   networks:
  #     - voltaris-network

  # Uncomment if you need a reverse proxy for multiple services
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./certbot/conf:/etc/letsencrypt:ro
  #     - ./certbot/www:/var/www/certbot:ro
  #   networks:
  #     - voltaris-network

networks:
  voltaris-network:
    driver: bridge

# Uncomment if you need persistent volumes
# volumes:
#   voltaris-db-data:
